#!/usr/bin/env bash
set -euo pipefail

APP_NAME="portcraft"
RELEASES_REPO="https://raw.githubusercontent.com/shunsing22/portcraft-releases/main"
DEFAULT_DIR="/opt/portcraft"

echo ""
echo "  PortCraft Installer"
echo "  ==================="
echo ""

# Check Docker
if ! command -v docker &>/dev/null; then
  echo "ERROR: Docker is not installed. Install Docker first:"
  echo "  https://docs.docker.com/engine/install/"
  exit 1
fi

if ! docker compose version &>/dev/null; then
  echo "ERROR: Docker Compose plugin not found."
  echo "  Install it via: https://docs.docker.com/compose/install/"
  exit 1
fi

# Install directory
read -rp "Install directory [$DEFAULT_DIR]: " INSTALL_DIR
INSTALL_DIR="${INSTALL_DIR:-$DEFAULT_DIR}"

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

echo "Downloading docker-compose.prod.yml..."
curl -fsSL "$RELEASES_REPO/docker-compose.prod.yml" -o docker-compose.yml

# Generate .env if it doesn't exist
if [ ! -f .env ]; then
  echo "Generating .env with random secrets..."
  POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)
  SECRET_KEY=$(openssl rand -base64 48 | tr -d '/+=' | head -c 48)

  cat > .env << ENVEOF
# PortCraft configuration — generated by installer
POSTGRES_USER=portcraft
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=portcraft
SECRET_KEY=$SECRET_KEY
HTTP_PORT=80
ENVEOF

  echo ".env created with random secrets."
else
  echo ".env already exists — keeping existing configuration."
fi

echo "Pulling Docker images..."
docker compose pull

echo "Starting PortCraft..."
docker compose up -d

echo ""
echo "PortCraft is running!"
echo "  Open http://localhost in your browser to complete setup."
echo ""
echo "  Install directory: $INSTALL_DIR"
echo "  To stop:   cd $INSTALL_DIR && docker compose down"
echo "  To update: cd $INSTALL_DIR && docker compose pull && docker compose up -d"
echo ""
