#!/usr/bin/env bash
set -euo pipefail

APP_NAME="portcraft"
RELEASES_REPO="https://raw.githubusercontent.com/shunsing22/portcraft-releases/main"
DEFAULT_DIR="/opt/portcraft"
DEFAULT_HTTP_PORT=80
DEFAULT_HTTPS_PORT=443

# When piped via curl|bash, stdin is consumed by the pipe.
# Only read needs /dev/tty — echo/printf output works normally.
prompt() {
  local varname="$1" prompt_text="$2"
  printf "%s" "$prompt_text"
  read -r "$varname" </dev/tty 2>/dev/null || eval "$varname=''"
}

prompt_secret() {
  local varname="$1" prompt_text="$2"
  printf "%s" "$prompt_text"
  read -rs "$varname" </dev/tty 2>/dev/null || eval "$varname=''"
  echo ""
}

echo ""
echo "  PortCraft Installer"
echo "  ==================="
echo ""

# ── Check prerequisites ──────────────────────────────────────────────

if ! command -v docker &>/dev/null; then
  echo "ERROR: Docker is not installed. Install Docker first:"
  echo "  https://docs.docker.com/engine/install/"
  exit 1
fi

if ! docker compose version &>/dev/null; then
  echo "ERROR: Docker Compose plugin not found."
  echo "  Install it via: https://docs.docker.com/compose/install/"
  exit 1
fi

# ── Gather configuration ─────────────────────────────────────────────

echo "  Server Configuration"
echo "  --------------------"
prompt INSTALL_DIR "  Install directory [$DEFAULT_DIR]: "
INSTALL_DIR="${INSTALL_DIR:-$DEFAULT_DIR}"

prompt HTTP_PORT "  HTTP port [$DEFAULT_HTTP_PORT]: "
HTTP_PORT="${HTTP_PORT:-$DEFAULT_HTTP_PORT}"

prompt HTTPS_PORT "  HTTPS port [$DEFAULT_HTTPS_PORT]: "
HTTPS_PORT="${HTTPS_PORT:-$DEFAULT_HTTPS_PORT}"

prompt SERVER_HOST "  Server hostname or IP (e.g. portcraft.example.com) [localhost]: "
SERVER_HOST="${SERVER_HOST:-localhost}"

# ── Gather admin account ─────────────────────────────────────────────

echo ""
echo "  Administrator Account"
echo "  ---------------------"

prompt ADMIN_USER "  Admin username: "
while [ -z "$ADMIN_USER" ]; do
  echo "  Username is required."
  prompt ADMIN_USER "  Admin username: "
done

prompt ADMIN_EMAIL "  Admin email: "
while [ -z "$ADMIN_EMAIL" ]; do
  echo "  Email is required."
  prompt ADMIN_EMAIL "  Admin email: "
done

while true; do
  prompt_secret ADMIN_PASS "  Admin password (min 8 chars): "
  if [ ${#ADMIN_PASS} -lt 8 ]; then
    echo "  Password must be at least 8 characters."
    continue
  fi
  prompt_secret ADMIN_PASS2 "  Confirm password: "
  if [ "$ADMIN_PASS" != "$ADMIN_PASS2" ]; then
    echo "  Passwords do not match."
    continue
  fi
  break
done

# ── Confirmation ─────────────────────────────────────────────────────

echo ""
echo "  Summary"
echo "  -------"
echo "  Install directory : $INSTALL_DIR"
echo "  HTTP port         : $HTTP_PORT"
echo "  HTTPS port        : $HTTPS_PORT"
echo "  Server host       : $SERVER_HOST"
echo "  Admin user        : $ADMIN_USER"
echo "  Admin email       : $ADMIN_EMAIL"
echo ""

prompt CONFIRM "  Proceed with installation? [Y/n]: "
CONFIRM="${CONFIRM:-Y}"
if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
  echo "Installation cancelled."
  exit 0
fi

echo ""

# ── Build CORS origins list ──────────────────────────────────────────

ALLOWED_ORIGINS="http://$SERVER_HOST"
if [ "$HTTP_PORT" != "80" ]; then
  ALLOWED_ORIGINS="http://$SERVER_HOST:$HTTP_PORT"
fi

# Add HTTPS origin
if [ "$HTTPS_PORT" = "443" ]; then
  ALLOWED_ORIGINS="$ALLOWED_ORIGINS,https://$SERVER_HOST"
else
  ALLOWED_ORIGINS="$ALLOWED_ORIGINS,https://$SERVER_HOST:$HTTPS_PORT"
fi

# Always include localhost for local access
if [ "$SERVER_HOST" != "localhost" ]; then
  ALLOWED_ORIGINS="$ALLOWED_ORIGINS,http://localhost"
  if [ "$HTTP_PORT" != "80" ]; then
    ALLOWED_ORIGINS="$ALLOWED_ORIGINS,http://localhost:$HTTP_PORT"
  fi
fi

# ── Set up install directory ─────────────────────────────────────────

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
mkdir -p certs

echo "Downloading docker-compose.yml..."
curl -fsSL "$RELEASES_REPO/docker-compose.yml" -o docker-compose.yml

# ── Generate .env ────────────────────────────────────────────────────

if [ ! -f .env ]; then
  echo "Generating .env with random secrets..."
  POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)
  SECRET_KEY=$(openssl rand -base64 48 | tr -d '/+=' | head -c 48)

  cat > .env << ENVEOF
# PortCraft configuration — generated by installer
POSTGRES_USER=portcraft
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=portcraft
SECRET_KEY=$SECRET_KEY
HTTP_PORT=$HTTP_PORT
HTTPS_PORT=$HTTPS_PORT
ALLOWED_ORIGINS=$ALLOWED_ORIGINS
ENVEOF

  echo ".env created."
else
  echo ".env already exists — updating ports and CORS..."
  sed -i "s|^HTTP_PORT=.*|HTTP_PORT=$HTTP_PORT|" .env
  sed -i "s|^HTTPS_PORT=.*|HTTPS_PORT=$HTTPS_PORT|" .env
  if grep -q "^ALLOWED_ORIGINS=" .env; then
    sed -i "s|^ALLOWED_ORIGINS=.*|ALLOWED_ORIGINS=$ALLOWED_ORIGINS|" .env
  else
    echo "ALLOWED_ORIGINS=$ALLOWED_ORIGINS" >> .env
  fi
  echo ".env updated."
fi

# ── Pull and start ───────────────────────────────────────────────────

echo "Pulling Docker images..."
docker compose pull

echo "Starting PortCraft..."
docker compose up -d

# ── Wait for backend to be ready ─────────────────────────────────────

API_URL="http://localhost:$HTTP_PORT/api"

echo "Waiting for backend to be ready..."
TRIES=0
MAX_TRIES=60
until curl -fsS "$API_URL/auth/status" >/dev/null 2>&1; do
  TRIES=$((TRIES + 1))
  if [ "$TRIES" -ge "$MAX_TRIES" ]; then
    echo ""
    echo "WARNING: Backend did not become ready after ${MAX_TRIES}s."
    echo "  You can create the admin account in the browser at:"
    if [ "$HTTP_PORT" = "80" ]; then
      echo "  http://$SERVER_HOST"
    else
      echo "  http://$SERVER_HOST:$HTTP_PORT"
    fi
    echo ""
    exit 0
  fi
  sleep 1
done

echo "Backend is ready."

# ── Create admin account ─────────────────────────────────────────────

echo "Creating administrator account..."
HTTP_CODE=$(curl -s -o /tmp/portcraft_setup.json -w "%{http_code}" \
  -X POST "$API_URL/auth/setup" \
  -H "Content-Type: application/json" \
  -d "{\"username\":\"$ADMIN_USER\",\"email\":\"$ADMIN_EMAIL\",\"password\":\"$ADMIN_PASS\"}")

if [ "$HTTP_CODE" = "200" ]; then
  echo "Admin account created successfully."
elif [ "$HTTP_CODE" = "400" ]; then
  echo "Admin account already exists — skipping."
else
  echo "WARNING: Failed to create admin account (HTTP $HTTP_CODE)."
  echo "  You can create it in the browser at the setup page."
fi

# Clean up
rm -f /tmp/portcraft_setup.json

# ── Done ─────────────────────────────────────────────────────────────

echo ""
echo "  PortCraft is running!"
if [ "$HTTP_PORT" = "80" ]; then
  echo "  Open http://$SERVER_HOST in your browser."
else
  echo "  Open http://$SERVER_HOST:$HTTP_PORT in your browser."
fi
echo ""
echo "  Install directory : $INSTALL_DIR"
echo "  Admin user        : $ADMIN_USER"
echo ""
echo "  To stop   : cd $INSTALL_DIR && docker compose down"
echo "  To update : cd $INSTALL_DIR && docker compose pull && docker compose up -d"
echo ""
