#Requires -Version 5.1
$ErrorActionPreference = "Stop"

$AppName = "portcraft"
$ReleasesRepo = "https://raw.githubusercontent.com/shunsing22/portcraft-releases/main"
$DefaultDir = "$env:USERPROFILE\portcraft"

Write-Host ""
Write-Host "  PortCraft Installer" -ForegroundColor Cyan
Write-Host "  ==================="
Write-Host ""

# Check Docker
try {
    docker --version | Out-Null
} catch {
    Write-Host "ERROR: Docker is not installed. Install Docker Desktop first:" -ForegroundColor Red
    Write-Host "  https://docs.docker.com/desktop/install/windows-install/"
    exit 1
}

try {
    docker compose version | Out-Null
} catch {
    Write-Host "ERROR: Docker Compose plugin not found." -ForegroundColor Red
    exit 1
}

# Install directory
$InstallDir = Read-Host "Install directory [$DefaultDir]"
if ([string]::IsNullOrWhiteSpace($InstallDir)) { $InstallDir = $DefaultDir }

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
Set-Location $InstallDir
New-Item -ItemType Directory -Force -Path "certs" | Out-Null

Write-Host "Downloading docker-compose.yml..."
Invoke-WebRequest -Uri "$ReleasesRepo/docker-compose.yml" -OutFile "docker-compose.yml" -UseBasicParsing

# Generate .env if it doesn't exist
if (-not (Test-Path ".env")) {
    Write-Host "Generating .env with random secrets..."

    $rng = [System.Security.Cryptography.RNGCryptoServiceProvider]::new()
    function Get-RandomString($length) {
        $bytes = New-Object byte[] $length
        $rng.GetBytes($bytes)
        return [Convert]::ToBase64String($bytes).Substring(0, $length) -replace '[/+=]', 'x'
    }

    $PostgresPassword = Get-RandomString 32
    $SecretKey = Get-RandomString 48

    @"
# PortCraft configuration — generated by installer
POSTGRES_USER=portcraft
POSTGRES_PASSWORD=$PostgresPassword
POSTGRES_DB=portcraft
SECRET_KEY=$SecretKey
HTTP_PORT=80
"@ | Set-Content -Path ".env" -Encoding UTF8

    Write-Host ".env created with random secrets."
} else {
    Write-Host ".env already exists — keeping existing configuration."
}

Write-Host "Pulling Docker images..."
docker compose pull

Write-Host "Starting PortCraft..."
docker compose up -d

Write-Host ""
Write-Host "PortCraft is running!" -ForegroundColor Green
Write-Host "  Open http://localhost in your browser to complete setup."
Write-Host ""
Write-Host "  Install directory: $InstallDir"
Write-Host "  To stop:   cd $InstallDir; docker compose down"
Write-Host "  To update: cd $InstallDir; docker compose pull; docker compose up -d"
Write-Host ""
